import type { ConnectorName } from '../types';

export interface ConnectorToolDelta {
  id: string;
  name?: string;
  input?: unknown;
  output?: unknown;
  /** Provider family that emitted this delta, when known. */
  provider?: Exclude<ConnectorName, 'auto'>;
  /** Real provider tool/function id. Omitted when `id` is a Chorus-generated fallback. */
  providerId?: string;
  /** True when `id` was generated by the connector because the provider did not send one. */
  generated?: boolean;
}

export interface ConnectorResult {
  text?: string;
  reasoning?: string;
  toolDelta?: ConnectorToolDelta;
  toolDeltas?: ConnectorToolDelta[];
  done?: boolean;
  error?: string;
  /** Original provider payload that produced an in-band connector error, when available. */
  errorPayload?: unknown;
}

export interface Connector<State = any> {
  name: string;
  /**
   * Optional per-send parser state. useChorusStream creates one state object for
   * every send() call and passes it back into extract() for each SSE payload.
   * Stateless custom connectors can omit this method and keep the classic
   * extract(data) shape.
   */
  createState?: () => State;
  extract(data: string, state?: State): ConnectorResult | null;
  /** Optional EOF hook for flushing connector buffers when a stream closes without a provider done sentinel. */
  flush?: (state?: State) => ConnectorResult | null;
}
