import type { ConnectorName } from '../types';

export interface ConnectorToolDelta {
  id: string;
  name?: string;
  input?: unknown;
  output?: unknown;
  /** Provider family that emitted this delta, when known. */
  provider?: Exclude<ConnectorName, 'auto'>;
  /** Real provider tool/function id. Omitted when `id` is a Chorus-generated fallback. */
  providerId?: string;
  /** True when `id` was generated by the connector because the provider did not send one. */
  generated?: boolean;
}

/**
 * Non-fatal connector signal that the stream should keep flowing but a consumer may want to
 * surface (e.g. truncation, safety ratings, telemetry events). Unlike `error`, a warning does
 * not abort the stream.
 */
export interface ConnectorWarning {
  /** Stable machine-readable identifier (e.g. `'truncated'`, `'safety-ratings'`, `'response-created'`). */
  code: string;
  /** Short human-readable description. */
  message: string;
  /** Original provider payload that produced the warning, when available. */
  payload?: unknown;
}

export interface ConnectorResult {
  text?: string;
  reasoning?: string;
  toolDelta?: ConnectorToolDelta;
  toolDeltas?: ConnectorToolDelta[];
  done?: boolean;
  error?: string;
  /** Original provider payload that produced an in-band connector error, when available. */
  errorPayload?: unknown;
  /**
   * Non-fatal connector warning (truncation, safety, refusal-coming, telemetry). Stream continues.
   * Kept as the legacy single slot — when a chunk carries several warnings it mirrors the first
   * entry of `warnings` for back-compat with consumers reading this field directly.
   */
  warning?: ConnectorWarning;
  /**
   * All non-fatal connector warnings produced by a single chunk. A chunk can legitimately carry
   * more than one independent diagnostic — e.g. an unsupported Gemini `inlineData` part *and*
   * `finishReason: MAX_TOKENS` truncation — and the single `warning` slot would silently drop
   * all but the first. Connectors that can emit several warnings populate this array; the
   * delivery pipeline routes every entry to `onWarning`, falling back to `warning` when absent.
   */
  warnings?: ConnectorWarning[];
  /**
   * Free-form provider metadata surfaced alongside text/reasoning (e.g. Anthropic `stop_reason`,
   * Gemini `safetyRatings`, OpenAI `usage`/`response.id`). The pipeline forwards it to the
   * `onMetadata` send callback (surfaced on `<Chorus>` as the `onStreamMetadata` prop and on
   * the `onSend` bridge via `helpers.streamCallbacks()`); it never affects rendering or
   * terminates the stream. Consumers wire it to persist or log usage/cost telemetry.
   */
  metadata?: Record<string, unknown>;
}

// `any` here is deliberate: lets `Connector<SomeState>` flow into APIs typed as
// plain `Connector` (e.g. registries, props) without contravariant-parameter errors.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface Connector<State = any> {
  name: string;
  /**
   * Optional per-send parser state. useChorusStream creates one state object for
   * every send() call and passes it back into extract() for each SSE payload.
   * Stateless custom connectors can omit this method and keep the classic
   * extract(data) shape.
   */
  createState?: () => State;
  extract(data: string, state?: State): ConnectorResult | null;
  /** Optional EOF hook for flushing connector buffers when a stream closes without a provider done sentinel. */
  flush?: (state?: State) => ConnectorResult | null;
}
